/**
 * 项目默认配置项
 * primaryColor - 默认主题色
 * navTheme - sidebar theme ['dark', 'light'] 两种主题
 * colorWeak - 色盲模式
 * layout - 整体布局方式 ['sidemenu', 'topmenu'] 两种布局
 * fixedHeader - 固定 Header : boolean
 * fixSiderbar - 固定左侧菜单栏 ： boolean
 * autoHideHeader - 向下滚动时，隐藏 Header : boolean
 * contentWidth - 内容区布局： 流式 |  固定
 *
 * storageOptions: {} - Vue-ls 插件配置项 (localStorage/sessionStorage)
 *
 */

export default {
  primaryColor: '#1890FF', // primary color of ant design
  navTheme: 'light', // theme for nav menu
  layout: 'sidemenu', // nav menu position: sidemenu or topmenu
  contentWidth: 'Fixed', // layout of content: Fluid or Fixed, only works when layout is topmenu
  fixedHeader: false, // sticky header
  fixSiderbar: false, // sticky siderbar
  autoHideHeader: false, //  auto hide header
  colorWeak: false,
  multipage: true, //默认多页签模式
  // vue-ls options
  storageOptions: {
    namespace: 'pro__', // key prefix
    name: 'ls', // name variable Vue.[ls] or this.[$ls],
    storage: 'local', // storage name session, local, memory
  },
  defaultMenuData: [
    {
      "redirect":null,
      "path":"/dashboard/analysis",
      "component":"dashboard/Analysis",
      "route":"1",
      "meta":{
          "keepAlive":true,
          "internalOrExternal":false,
          "icon":"home",
          "title":"首页"
      },
      "name":"dashboard-analysis",
      "id":"9502685863ab87f0ad1134142788a385"
    },
    {
        "redirect":null,
        "path":"/isystem",
        "component":"layouts/RouteView",
        "route":"1",
        "children":[
            {
                "path":"/isystem/user",
                "component":"system/UserList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"用户管理"
                },
                "name":"isystem-user",
                "id":"3f915b2769fc80648e92d04e84ca059d"
            },
            {
                "path":"/isystem/newPermissionList",
                "component":"system/NewPermissionList",
                "route":"1",
                "meta":{
                    "keepAlive":true,
                    "internalOrExternal":false,
                    "title":"菜单管理"
                },
                "name":"isystem-newPermissionList",
                "id":"1170592628746878978"
            },
            {
                "path":"/isystem/roleUserList",
                "component":"system/RoleUserList",
                "route":"1",
                "meta":{
                    "keepAlive":true,
                    "internalOrExternal":false,
                    "title":"角色管理"
                },
                "name":"isystem-roleUserList",
                "id":"190c2b43bec6a5f7a4194a85db67d96a"
            },
            {
                "path":"/isystem/depart",
                "component":"system/DepartList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"部门管理"
                },
                "name":"isystem-depart",
                "id":"45c966826eeff4c99b8f8ebfe74511fc"
            },
            {
                "path":"/isystem/departUserList",
                "component":"system/DepartUserList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"我的部门"
                },
                "name":"isystem-departUserList",
                "id":"5c2f42277948043026b7a14692456828"
            },
            {
                "path":"/isystem/position",
                "component":"system/SysPositionList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"职务管理"
                },
                "name":"isystem-position",
                "id":"1174506953255182338"
            },
            {
                "path":"/isystem/dict",
                "component":"system/DictList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"数据字典"
                },
                "name":"isystem-dict",
                "id":"f1cb187abf927c88b89470d08615f5ac"
            },
            {
                "path":"/isys/category",
                "component":"system/SysCategoryList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"分类字典"
                },
                "name":"isys-category",
                "id":"ebb9d82ea16ad864071158e0c449d186"
            },
            {
                "path":"/isystem/annountCement",
                "component":"system/SysAnnouncementList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"系统通告"
                },
                "name":"isystem-annountCement",
                "id":"e08cb190ef230d5d4f03824198773950"
            }
        ],
        "meta":{
            "keepAlive":false,
            "internalOrExternal":false,
            "icon":"setting",
            "title":"系统管理"
        },
        "hidden": true,
        "name":"isystem",
        "id":"d7d6e2e4e2934f2c9385a623fd98c6f3"
    },
    {
        "redirect":null,
        "path":"/account",
        "component":"layouts/RouteView",
        "route":"1",
        "hidden":true,
        "children":[
            {
                "path":"/account/center",
                "component":"account/center/Index",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"个人中心"
                },
                "name":"account-center",
                "id":"d86f58e7ab516d3bc6bfb1fe10585f97"
            },
            {
                "path":"/account/settings/Index",
                "component":"account/settings/Index",
                "route":"1",
                "children":[
                    {
                        "path":"/account/settings/notification",
                        "component":"account/settings/Notification",
                        "route":"1",
                        "meta":{
                            "keepAlive":false,
                            "internalOrExternal":false,
                            "title":"新消息通知"
                        },
                        "name":"account-settings-notification",
                        "id":"fedfbf4420536cacc0218557d263dfea"
                    },
                    {
                        "path":"/account/settings/custom",
                        "component":"account/settings/Custom",
                        "route":"1",
                        "meta":{
                            "keepAlive":false,
                            "internalOrExternal":false,
                            "title":"个性化设置"
                        },
                        "name":"account-settings-custom",
                        "id":"882a73768cfd7f78f3a37584f7299656"
                    },
                    {
                        "path":"/account/settings/binding",
                        "component":"account/settings/Binding",
                        "route":"1",
                        "meta":{
                            "keepAlive":false,
                            "internalOrExternal":false,
                            "title":"账户绑定"
                        },
                        "name":"account-settings-binding",
                        "id":"4f66409ef3bbd69c1d80469d6e2a885e"
                    },
                    {
                        "path":"/account/settings/BaseSetting",
                        "component":"account/settings/BaseSetting",
                        "route":"1",
                        "hidden":true,
                        "meta":{
                            "keepAlive":false,
                            "internalOrExternal":false,
                            "title":"基本设置"
                        },
                        "name":"account-settings-base",
                        "id":"1367a93f2c410b169faa7abcbad2f77c"
                    },
                    {
                        "path":"/account/settings/security",
                        "component":"account/settings/Security",
                        "route":"1",
                        "meta":{
                            "keepAlive":false,
                            "internalOrExternal":false,
                            "title":"安全设置"
                        },
                        "name":"account-settings-security",
                        "id":"ec8d607d0156e198b11853760319c646"
                    }
                ],
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"个人设置"
                },
                "name":"account-settings-Index",
                "id":"6e73eb3c26099c191bf03852ee1310a1",
                "alwaysShow":true
            },
            {
                "path":"/dashboard/workplace",
                "component":"dashboard/Workplace",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"工作台"
                },
                "name":"dashboard-workplace",
                "id":"8fb8172747a78756c11916216b8b8066"
            }
        ],
        "meta":{
            "keepAlive":false,
            "internalOrExternal":false,
            "icon":"user",
            "title":"个人页"
        },
        "name":"account",
        "id":"717f6bee46f44a3897eca9abd6e2ec44"
    },
    {
        "redirect":null,
        "path":"/dashboard3",
        "component":"layouts/RouteView",
        "route":"1",
        "children":[
            {
                "path":"/isps/userAnnouncement",
                "component":"system/UserAnnouncementList",
                "route":"1",
                "meta":{
                    "keepAlive":false,
                    "internalOrExternal":false,
                    "title":"我的消息"
                },
                "name":"isps-userAnnouncement",
                "id":"53a9230444d33de28aa11cc108fb1dba"
            }
        ],
        "meta":{
            "keepAlive":false,
            "internalOrExternal":false,
            "icon":"dashboard",
            "title":"系统监控"
        },
        "name":"dashboard3",
        "id":"08e6b9dc3c04489c8e1ff2ce6f105aa4"
    },
    {
      "redirect":null,
      "path":"/exception",
      "component":"layouts/RouteView",
      "route":"1",
      "children":[
          {
              "path":"/exception/403",
              "component":"exception/403",
              "route":"1",
              "meta":{
                  "keepAlive":false,
                  "internalOrExternal":false,
                  "title":"403"
              },
              "name":"exception-403",
              "id":"65a8f489f25a345836b7f44b1181197a"
          },
          {
              "path":"/exception/404",
              "component":"exception/404",
              "route":"1",
              "meta":{
                  "keepAlive":false,
                  "internalOrExternal":false,
                  "title":"404"
              },
              "name":"exception-404",
              "id":"d2bbf9ebca5a8fa2e227af97d2da7548"
          },
          {
              "path":"/exception/500",
              "component":"exception/500",
              "route":"1",
              "meta":{
                  "keepAlive":false,
                  "internalOrExternal":false,
                  "title":"500"
              },
              "name":"exception-500",
              "id":"b4dfc7d5dd9e8d5b6dd6d4579b1aa559"
          }
      ],
      "meta":{
          "keepAlive":false,
          "internalOrExternal":false,
          "icon":"warning",
          "title":"异常页"
      },
      "name":"exception",
      "id":"c65321e57b7949b7a975313220de0422"
    }
  ]
}